# Generated by Django 6.0 on 2026-01-25 08:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatConversaciones',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_conversaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMensajes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_mensajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiudadanoDocumentos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('url_frontal', models.TextField(blank=True, null=True)),
                ('url_trasera', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ciudadano_documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'denuncias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaAsignaciones',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asignado_en', models.DateTimeField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'denuncia_asignaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaBorradores',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('datos_json', models.JSONField()),
                ('listo_para_enviar', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncia_borradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaEvidencias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('url_archivo', models.TextField()),
                ('nombre_archivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncia_evidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaFirmas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firma_url', models.TextField(blank=True, null=True)),
                ('firma_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncia_firmas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaHistorial',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('estado_anterior', models.TextField(blank=True, null=True)),
                ('estado_nuevo', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncia_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaRespuesta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
            ],
            options={
                'db_table': 'denuncia_respuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DenunciaRespuestas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncia_respuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion_texto', models.TextField(blank=True, null=True)),
                ('origen', models.TextField()),
                ('estado', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('visible', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionarioRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'funcionario_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('leido', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetTokens',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_6', models.CharField(max_length=6)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDenuncia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tipos_denuncia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudadanos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.usuarios')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil_url', models.TextField(blank=True, null=True)),
                ('firma_url', models.TextField(blank=True, null=True)),
                ('firma_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ciudadanos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.usuarios')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDenunciaDepartamento',
            fields=[
                ('tipo_denuncia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.tiposdenuncia')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tipo_denuncia_departamento',
                'managed': False,
            },
        ),
    ]
