# Generated by Django 6.0 on 2026-02-16 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorArchivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cedula', 'cedula'), ('firma', 'firma'), ('foto', 'foto'), ('audio', 'audio'), ('video', 'video')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrador', models.ForeignKey(db_column='borrador_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='db.denunciaborradores')),
            ],
            options={
                'db_table': 'borrador_archivos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenunciaArchivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cedula', 'cedula'), ('firma', 'firma'), ('foto', 'foto'), ('audio', 'audio'), ('video', 'video')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(db_column='denuncia_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='db.denuncias')),
            ],
            options={
                'db_table': 'denuncia_archivos',
                'managed': True,
            },
        ),
    ]
