# Generated by Django 5.2.7 on 2026-01-11 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('url', models.CharField(db_column='url', max_length=200)),
                ('icono', models.CharField(blank=True, db_column='icono', max_length=100, null=True)),
                ('orden', models.IntegerField(db_column='orden', default=0)),
                ('padre', models.ForeignKey(blank=True, db_column='padre_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='web.menus')),
            ],
            options={
                'db_table': 'menus',
                'ordering': ['orden'],
            },
        ),
    ]
