# Generated by Django 5.2.7 on 2026-01-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='permission_required',
            field=models.CharField(blank=True, help_text='Permiso requerido para ver este menú (ej: auth.view_user)', max_length=150, null=True),
        ),
    ]
