# Generated by Django 5.2.7 on 2026-01-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0002_menus_permission_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='permission_required',
        ),
        migrations.AddField(
            model_name='menus',
            name='permisos',
            field=models.ManyToManyField(blank=True, db_table='menu_permisos', related_name='menus', to='auth.group'),
        ),
    ]
