# Generated by Django 6.0 on 2026-01-25 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('web', '0003_remove_menus_permission_required_menus_permisos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioWebUser',
            fields=[
                ('funcionario', models.OneToOneField(db_column='funcionario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='web_link', serialize=False, to='db.funcionarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_user', models.OneToOneField(db_column='web_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funcionario_web_user',
            },
        ),
    ]
