# Generated by Django 6.0 on 2026-02-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0004_funcionariowebuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={},
        ),
        migrations.AlterField(
            model_name='menus',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menus',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menus',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='web.menus'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='menus_visibles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='menus',
            table=None,
        ),
    ]
