"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

FIREBASE_SERVICE_ACCOUNT_PATH = os.getenv(
    "FIREBASE_SERVICE_ACCOUNT_PATH",
    str(BASE_DIR / "serviceAccountKey.json")
)


load_dotenv(BASE_DIR / ".env")
 # importando ia
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wy$n=-=p&=y2ic4!j2tpvis)5hl0l*3$1o5q7od64#rz-l&g2+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


#ruta
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.100.46"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # terceros
    "rest_framework",
    "corsheaders",
    "django_extensions",
    "django_select2",
    'chartkick.django',
    #rutas
    "usuarios_api",
    "denuncias_api",
    "catalogos_api",
    "db",
    #"web",
    "web.apps.WebConfig",
    #librerias
    "crispy_forms",
    "crispy_bootstrap5",
    #notificaciones push
     "notificaciones",
     
    
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", #esta ruta se agrego
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web.context_processors.menu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
CORS_ALLOW_ALL_ORIGINS = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
DEFAULT_CHARSET = "utf-8"

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_REDIRECT_URL = 'web:home'
LOGIN_URL = 'web:login'

# Manejadores de errores personalizados
HANDLER403 = 'web.views.permission_denied_view'
HANDLER404 = 'web.views.page_not_found_view'
HANDLER500 = 'web.views.server_error_view'

# drf config
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
       # "rest_framework_simplejwt.authentication.JWTAuthentication",
         "usuarios_api.authentication.UsuariosJWTAuthentication",
    
    ),
}
DEFAULT_DEPARTAMENTO_ID = int(os.getenv("DEFAULT_DEPARTAMENTO_ID", "5"))

from datetime import timedelta
SIMPLE_JWT = {
    "USER_ID_CLAIM": "uid",
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

#subir envidencias
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Configuración de caché para django-select2 (sin Redis)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Configuración de django-select2
SELECT2_CACHE_BACKEND = "default"

# no cree migraciones
"""MIGRATION_MODULES = {
    "db": None,
}"""

#------
import certifi
os.environ["SSL_CERT_FILE"] = certifi.where()


# CONFIGURACION SMTP DE GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tuhackerfav9@gmail.com' # Tu correo electrónico
EMAIL_HOST_PASSWORD = 'tmnc pypb tomd oylb' # Tu contraseña de aplicación de Gmail




#librerias
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


