# Generated by Django 5.2.7 on 2026-01-10 23:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCiudadanoBorrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo_6', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_expira', models.DateTimeField(blank=True, null=True)),
                ('correo_verificado', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cedula_frontal_url', models.TextField(blank=True, null=True)),
                ('cedula_trasera_url', models.TextField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'registro_ciudadano_borrador',
                'managed': False,
            },
        ),
    ]
